# Generated by Django 4.2.23 on 2025-06-28 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='fare',
            new_name='final_fare',
        ),
        migrations.AddField(
            model_name='ride',
            name='accepted_proposal',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='distance_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='driver_proposals',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='ride',
            name='estimated_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='eta_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='passenger_counter_offers',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='ride',
            name='proposal_type',
            field=models.CharField(choices=[('passenger', 'Passenger Proposal'), ('driver', 'Driver Proposal')], default='passenger', max_length=10),
        ),
        migrations.AddField(
            model_name='ride',
            name='proposed_fare',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.CreateModel(
            name='DriverNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('score', models.FloatField()),
                ('details', models.JSONField()),
                ('responded', models.BooleanField(default=False)),
                ('response_time', models.FloatField(null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rides.ride')),
            ],
            options={
                'indexes': [models.Index(fields=['driver', 'responded'], name='rides_drive_driver__cf2236_idx'), models.Index(fields=['score'], name='rides_drive_score_bfdb36_idx')],
            },
        ),
    ]
