# Generated by Django 4.2.23 on 2025-06-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers_user_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='average_fare',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='avg_response_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='current_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
